### ISSUE TITLE
Syntax error: Unexpected token export

### ISSUE THREAD

**Issue by maylortaylor** [nestjs-community/nestjs-flub#18]
I'm trying to put this into my NestJs app. I put `@UseFilters(new FlubErrorHandler({ theme: 'dark', quote: true }))` above my HomeController (and below `@Controller('home')`.

I then put this at the top of the file: `import { FlubErrorHandler } from 'nestjs-flub';`

When i run the app. i get the following error.
I was really hoping to use this as a GlobalFilter like this `app.useGlobalFilters(new FlubErrorHandler());` in my `main.ts`... or better yet, have it be apart of my global error filter class like this `@Catch(MessageCodeError, ValidationError, HttpException, Error)`

The error below is pointing out "export".

~app/node_modules/nestjs-flub/src/index.ts:1
(function (exports, require, module, __filename, __dirname) { export { FlubErrorHandler } from './flub-error-handler';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/maylortaylor/Dropbox/Dev/_Bovsi/BovsiSocialBots/Bovsi-LinkedIn/LinkedInBot/node_modules/ts-node/src/index.ts:431:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)

**Comment by priyankajain9833** [comment]
a new version of what?

**Comment by manasdwd07** [comment]
Hey did you find the solution for this one ? 
My idea is to configure babel so as to make the syntax according to ES5. 

Please do attach the solution :)
